<h1>Inscríbete</h1>
<div class="row">
    <form method="post" action="/seleccion">
    <div class="col-md-6">
        <p style="text-align: right"> Equipos disponibles: <b><?php echo $lugares_disponibles?></b></p>
        <div class="form-group">
            <label for="exampleInputEmail1">Nombre</label>
            <input type="text" name="nombre" class="form-control" style="text-transform: uppercase;" required>
            
        </div>
        <div class="form-group">
            <input type="submit" class="btn btn-success" value="OK!"> 
        </div>
    </div>
    </form>
</div>